return {
	pde = {
		ai = false,
		angular = false,
		cpp = false,
		csharp = false,
		docker = false,
		elixir = false,
		flutter = false,
		go = true,
		html = false,
		java = false,
		json = false,
		julia = false,
		jupyter = false,
		kotlin = false,
		lua = true,
		python = true,
		r = false,
		react = false,
		ruby = false,
		rust = false,
		scala = false,
		solidity = false,
		svelte = false,
		tailwind = false,
		terraform = false,
		typescript = false,
		vuejs = false,
		yaml = true,
	},
}
